# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74eef251197387447c725926c4d70e5642547040b1c3a5a59194ffc9f99adae0d6420d0d2c9684e6459f44d270d344cc7891d61b1af41d6396cdc46f195e6da7

test:
  secret_key_base: 6c7a596c931dc2761df4176e6cd36b51038a90d0ccd8663b7b4b47f8801f155113d57c7452ee6d935f5ce580e2c36f24853e05444ee0cb8e9fc039e4a9f79669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
